services:
  - type: web
    name: mundus-editor-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://mundus-editor-backend.onrender.com
    staticPublishPath: dist

  - type: web
    name: mundus-editor-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/backend.py
    envVars:
      - key: OPENAI_API_KEY
        fromService:
          name: mundus-editor-backend
          type: env
          property: OPENAI_API_KEY
      - key: FLASK_ENV
        value: production 